services:
  app:
    container_name: mainstack_product_store
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5500"
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URI=${DATABASE_URI}
    env_file:
      - .env
